### ISSUE TITLE
Deleting a calendar

### ISSUE THREAD

**Issue by dpraul** [natelindev/tsdav#100]
Hello! I'm still a novice with CalDAV, so apologies if this question has an obvious answer. It seems straightforward to create and query calendars with this library, but is there any capability to delete calendars?

**Comment by natelindev** [comment]
just call deleteObject on the calendar url

Dylan Praul ***@***.***>于2022年3月17日 周四04:43写道：

**Comment by dpraul** [comment]
Perfect, love a simple and straightforward solution. Thank you!
