### ISSUE TITLE
Rollup is requested as a peer dependency from one of tsdav direct dependencies

### ISSUE THREAD

**Issue by denik1981** [natelindev/tsdav#103]
When using **tsdav** I'm getting a warning (from yarn in this case) of an unmet peer dependency for **rollup**.

```
"workspace-aggregator-165f5ad3-7952-4846-9cdd-20e379f7ba54 > @calcom/web > tsdav > rollup-plugin-polyfill-node > @rollup/plugin-inject > @rollup/pluginutils@3.1.0" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
```

As rollup is being added as a devDependency here, it will force any project using tsdav to add it as dependency in order to remove this warning unless it is imported as a dependency (not devDep) here in tsdav.

Rollup is a peer dep of the rollup-plugin-polyfill-node package which is a direct dependency of tsdav. 
Being tsdav a lib and not a standalone project I feel it should be here where rollup should be added as a dependency and not in the project using tsdav.

**Comment by natelindev** [comment]
I will solve this issue later this week.
It's a slight mistake, moving rollup related packages to devDep should be the solution.
