### ISSUE TITLE
Fetch public calendars

### ISSUE THREAD

**Issue by Th30n3and0nly** [natelindev/tsdav#107]
Is there a way to fetch public (nextcloud) calendars with tsdav? I.e. without authenticating against the server.

**Comment by natelindev** [comment]
You can use `fetchCalendarObjects ` function without passing header parameter and a `DAVCalendar` with only public calendar url.

**Comment by Th30n3and0nly** [comment]
Thanks for the quick reply. In contrast to nextclouds private calendar link (which leads to a caldav interface) the public link in nextcloud just opens up a regular html/gui version of the calendar. Therefore my approach fails. Thanks anyway.

**Comment by adalanerd** [comment]
Hello @natelindev,
Thanks for your work on this lib!
I'm sorry tho because I don't understand how to create a DAVCalendar object without creating a DAVClient first. I can't find it anywhere in the docs.
I hope you can help me on this!
Thanks again
