### ISSUE TITLE
Add an example of loading a calendar with only access_token without a davClient.

### ISSUE THREAD

**Issue by lowfront** [natelindev/tsdav#115]
Hello, thank you so much for creating a library before the issue.

I am currently working on sync Google calendar with Electron, and I made a separate server for token issuance because I don't want to store client_secret inside Electron code.

In this way, why don't you include a manual use case of issuing refresh_token without using client_secret? It's something I can understand by reading the document, but it takes time to figure out what I need, so I suggest it.

```js
import { createAccount, fetchCalendars, fetchCalendarObjects } from 'tsdav';

const headers = {
  authorization: `Bearer <google_access_token>`,
};

const account = await createAccount({
  account: { 
    serverUrl: 'https://apidata.googleusercontent.com/caldav/v2/',
    accountType: 'caldav',
  },
  headers,
});

const calendars = await fetchCalendars({
  account,
  headers,
});

const calendarObjects = await fetchCalendarObjects({
  calendar: calendars[0],
  headers,
});
```

**Comment by natelindev** [comment]
Thanks for the suggestion, I'll add a new section in the docs later.
