### ISSUE TITLE
caldav create/update/delete response

### ISSUE THREAD

**Issue by strukturart** [natelindev/tsdav#125]
Hello,

Is it possible to get a response back with the new etag if you have created a calendar object?

**Comment by natelindev** [comment]
Yes, caldav implementations vary a lot from provider to provider.
I wouldn't bet on the server always returning etag.

a better solution is to use `propfind` to manually query the etag of resource you've just created, like:

```ts
await createObject({
  url: objectUrl1,
  data: iCalString1,
  headers: {
    'content-type': 'text/calendar; charset=utf-8',
    ...authHeaders,
  },
});

const [result] = await propfind({
  url: objectUrl1,
  props: {
    [`${DAVNamespaceShort.DAV}:getetag`]: {},
  },
  depth: '0',
  headers: authHeaders,
});

console.log(result.props?.getetag);
// outputs: l5guvnaq which is the etag of the created object.
```

**Comment by strukturart** [comment]
thanks that works!
