### ISSUE TITLE
google oauth "Invalid grant_type: "

### ISSUE THREAD

**Issue by strukturart** [natelindev/tsdav#130]
hello,

I'm trying to try out your oauth helper but when using` getOauthHeaders` I get the error message: 
```
error"unsupported_grant_type"
error_description"Invalid grant_type: "
```

`result{"tokens":{},"headers":{"authorization":"Bearer undefined"}}`

```
let test = function () {
  (async () => {
    try {
      const tokens = await getOauthHeaders({
        authorizationCode: localStorage.getItem("authorizationCode"),
        clientId: google_cred.clientId,
        clientSecret: google_cred.clientSecret,
        tokenUrl: "https://accounts.google.com/o/oauth2/token",
        redirectUrl: "https://strukturart.github.io/greg/",
      });
      console.log("result" + JSON.stringify(tokens));
    } catch (e) {
      console.log("error" + e);
    }
  })();
}
```

what am I doing wrong ?

**Comment by natelindev** [comment]
`redirectUrl` need to be url encoded and registered in google api console.
I checked the code and `authorization_code` is a valid grant type accroding to google api doc.

**Comment by strukturart** [comment]
Thank you for your answer. I found out why it didn't work. I use tsdav under KaiOs which is based on ff 48, `toString()` is not supported there, which I have now retrofitted with a polyfill.
