### ISSUE TITLE
client.smartCollectionSync detailedResult can't be passed as true

### ISSUE THREAD

**Issue by swkoyo** [natelindev/tsdav#131]
Hey there,

It seems there's a bug within the type declaration. The function `smartCollectionSync` doesn't allow `detailedResult` to be passed as `true` (can only be passed as `undefined` or `false`).  

![image](https://user-images.githubusercontent.com/10441291/190595035-70594992-6aa6-4e34-89ef-b99bf860310b.png)
![image](https://user-images.githubusercontent.com/10441291/190595113-2f7459f6-894d-452a-939e-e409d17d68e5.png)

When I set it to `true as false`, the expected response is received.

![image](https://user-images.githubusercontent.com/10441291/190595271-90eeedb1-5406-44f2-a39a-8e277367d48e.png)
![image](https://user-images.githubusercontent.com/10441291/190595306-cd3fd09f-c6d6-4064-b382-640cee25a0c1.png)

The documentation shows that `detailedResult` can be passed as `true` so I assume this should be valid. I'm not familiar with caldav so I might be making the wrong assumption though.

**Comment by natelindev** [comment]
Thanks for suggestions, I'll investigate it and get back to you soon.

**Comment by natelindev** [comment]
cannot repo
sample code used to repo,
no error occurred.

```ts

const icalCalendar = {
  url: 'https://example.com/calendars/icalendar.ics',
};
const icalData: DAVObject[] = [];

(async () => {
  const data = await smartCollectionSync({
    collection: {
      ...icalCalendar,
      objects: icalData,
    },
    method: 'webdav',
    detailedResult: false,
  });
})();

```

both true and false should be able to be passed in.
