### ISSUE TITLE
Sync Calendar Issue

### ISSUE THREAD

**Issue by shishirchulliyil** [natelindev/tsdav#138]
Hi @natelindev, we are trying to sync our application events to Apple Device Calendar. 
1. We have a scheduled auto sync, and on every sync we delete all the calendar objects using deleteCalendarObject API.
2. We re-insert using the createCalendarObject API.
3. But on every auto sync, duplicate events are showing on Apple Devices, and it is not consistent on all device. Some device shows duplicate events on the apple calendar app and some don't.
4. Just to note, when we visit iCloud.com/calendar, we see there are single events, but when the auto sync is happening we see the events getting duplicated, but as soon as the auto sync completes and we refresh the browser tab, we see again only the single events which is the expected result.

We have used the same API for Outlook and Google Calendar also, but we don't see any duplicate events there. Is our approach (deleting and re adding Calendar Objects) wrong for Auto Sync or is there a better way to achieve this? Is there any caching issue which we might be dealing with the Apple devices?

We also tried using the syncCalendars API but we are not sure what happens, does the calendar automatically syncs with the updated data or do we have to do something with the returned response from the API?

**Comment by strukturart** [comment]
https://github.com/natelindev/tsdav/issues/124

I use https://tsdav.vercel.app/docs/caldav/syncCalendars to test if there was a change in a calendar if yes, then I delete all events locally and fetch all calendar data again.

**Comment by natelindev** [comment]
> #124
> 
> I use https://tsdav.vercel.app/docs/caldav/syncCalendars to test if there was a change in a calendar if yes, then I delete all events locally and fetch all calendar data again.

This is very ineffecient, I will provide an example later for all use cases.

**Comment by natelindev** [comment]
Currently the documentation related to syncing is not very clear, I will provide some detail examples and code snippets to make it more clear.

**Comment by strukturart** [comment]
@natelindev  can you please explain how to find out which calendar entries are new, updated or deleted?

**Comment by natelindev** [comment]
fixed in v2.0.9, please read the lastest docs
