### ISSUE TITLE
$2,000 Bounty to add more support

### ISSUE THREAD

**Issue by PeerRich** [natelindev/tsdav#140]
Hey TSDav gang. I just raised a bounty of $2,000 to add more support for more CalDav services:

https://github.com/calcom/cal.com/issues/3457#issuecomment-1435999404

**Comment by natelindev** [comment]
Sorry I didn't find time for adding more support for caldav, too much things happened in my life.
Glad I'm able to find time for open source work now again.

**Comment by PeerRich** [comment]
would you be interested if we take over the repo?
