### ISSUE TITLE
Support for digest authentication

### ISSUE THREAD

**Issue by KiqoCode** [natelindev/tsdav#144]
Hi,

I was wondering if there is any plan to implement support for digest authentication type? 
Some calendar clients (such as Mac OSX Calendar) seem to only support digest and not basic, so when using a calendar server like baikal, we have to use digest if we want to be able to administrate the calendar with ex. OSX Calendar app. 

So it would be a really nice feature to support digest in tsdav as well.

**Comment by natelindev** [comment]
Digest auth is indeed very useful, will add it in the next release

**Comment by natelindev** [comment]
fixed in v2.0.5
