### ISSUE TITLE
Update cross-fetch to 4.0.0

### ISSUE THREAD

**Issue by ocavue** [natelindev/tsdav#159]
`cross-fetch@4.0.0` fixed this [issue](https://github.com/lquixada/cross-fetch/issues/69) when running `tsdav` on Cloudflare Worker or Vercel Edge Runtime.

**Comment by natelindev** [comment]
will update soon.

**Comment by natelindev** [comment]
fixed in v2.0.6

**Comment by strukturart** [comment]
This means that tsdav can now also be used in a service worker ?
