### ISSUE TITLE
Unable to use TSdav with Mdaemon

### ISSUE THREAD

**Issue by rdenarie** [natelindev/tsdav#166]
I'm trying to use tsdav library against Mdaemon caldav server.

I haev a CORS problem when using createCalendarObject to push an event in the calendar

In fact, in the request, I can see this header : 
![image](https://github.com/natelindev/tsdav/assets/807839/dffce5a7-5564-45e7-9176-18cdc3130996)

Tsdav correctly provide header he will need to read.
But Mdaemon answer this : 
![image](https://github.com/natelindev/tsdav/assets/807839/22f6a34d-dc63-4f8e-8b21-a5273c5885ea)
and 
![image](https://github.com/natelindev/tsdav/assets/807839/970c19e1-9b09-4189-bf13-31c83c94b7d7)

Mdaemon seems not read the request header Access-Control-Request-Headers, and as, in createCalendarObject, tsdav add the header If-None-Match: *, the PUT request fails.

I didnt manage to find a way to configure the Mdaemon server to correctly accept this header. 

So there is a way to have an option in tsdav, to allow to deactivate the header If-None-Match ?

Thanks

**Comment by natelindev** [comment]
will add an option to disable this in the next version

**Comment by rdenarie** [comment]
Hello, thanks a lot for your answer !

**Comment by natelindev** [comment]
fixed in v2.0.7
