### ISSUE TITLE
Missing `DTEND` from Synology Calendar CALDAV

### ISSUE THREAD

**Issue by eouia** [natelindev/tsdav#180]
When I parse the calendars from Synology NAS calendar CalDAV, the result of parsing would miss DTEND, only DURATION existed. That makes some error on consuming the parsing result.

The code that I used to get is;
```js
const { DAVClient, DAVNamespace } = require('tsdav')

 const client = new DAVClient({ ... })

const fetchedCalendars = await client.fetchCalendars()
  for (let calendar of fetchedCalendars) {
    const objects = await client.fetchCalendarObjects({
      calendar,
    })
    ...
```

It will return something like this.
```txt
BEGIN:VEVENT
CREATED:20240215T101655
LAST-MODIFIED:20240215T101655
DTSTAMP:20240215T101655
UID:20240215T101655-b6e4bbe9@192.168.178.100
SEQUENCE:2
SUMMARY:period test2
TRANSP:OPAQUE
DESCRIPTION:
LOCATION:Kriftel
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-TITLE=Kriftel:
 geo:50.083558\,8.4693855
DTSTART:20240215T090000Z
DURATION:PT15M
END:VEVENT
```
Originally that event was this; 
<img width="470" alt="image" src="https://github.com/natelindev/tsdav/assets/1720610/4b74d00d-6ec5-41ef-8c98-63af52c06f13">

Usually, feeds from other CalDAV provider (e.g. Google Calendar) are OK. Only feed from Synology Calendar has this symptom.
(Synology Calendar version: 2.4.6-20944 / Synology DSM 7.2.1-69057 Update 3 / Hardware DS920+)

As far as I know, RFC 5545 will regard, "date-time" type DTSTART without DTEND as a momently finished event. So this needs some help.

Could you take a look at this?

**Comment by natelindev** [comment]
I'll look into it today.

**Comment by natelindev** [comment]
I don't think this is related to caldav.
As the spec speificifed:
when an event has one of 
`DTEND` and `DURATION` it's considered valid.
Also all day events will only have `DTSTART` with neither `DTEND` nor `DURATION`.

Many caldav API providers will have their own unique ways to store the ics content.
This lib's job is only to deliver the data between the server and client.

To parse/convert the actual event data format, you can try using https://github.com/nwcell/ics.js/ or other ics file processing libs.

**Comment by eouia** [comment]
You are right. Thanks.
