### ISSUE TITLE
fetchCalendars throws error 'Cannot read properties of undefined (reading '_attributes')'

### ISSUE THREAD

**Issue by Jiaunian** [natelindev/tsdav#181]
![image](https://github.com/natelindev/tsdav/assets/66256045/05e8fc34-09d3-4931-bc90-c313ebc6901c)

I ran into an issue when connecting to support other calendars (企业微信) using TSDAV with the CalDAV protocol, as shown in the above picture. After testing, I found that making the following modifications will allow it to function properly.

![image](https://github.com/natelindev/tsdav/assets/66256045/2a5c21c6-e9a0-4a16-9596-a54ab8cb77aa)

**Comment by natelindev** [comment]
will fix today

**Comment by natelindev** [comment]
fixed ,will add to next release

**Comment by natelindev** [comment]
fixed in v2.0.9

**Comment by quanru** [comment]
@junjiantech Can you use it normally under Enterprise WeChat? I have encountered the problem of 403 here!

**Comment by junjiantech** [comment]
> @junjiantech Can you use it normally under Enterprise WeChat? I have encountered the problem of 403 here!

Yes, it is available now.
