### ISSUE TITLE
CORS problem trying to request a icloud calendars

### ISSUE THREAD

**Issue by tised** [natelindev/tsdav#187]
Here's the issue:
![image](https://github.com/natelindev/tsdav/assets/14261987/5af6ec62-3cf1-4ec2-8bc5-15ba632ac32b)

Here the code which are causing the issue, I **removed** user name and password for the screenshot purposes, there are my apple id and a password generated from appleid 
![image](https://github.com/natelindev/tsdav/assets/14261987/85c3b22a-2b23-4670-b24f-166adc1bca4b)

**Comment by natelindev** [comment]
while the lib can work on frontend, 
it's usually recommended to only use it with your own self hosted caldav servers which you can control the cros headers.

Cloud caldav service providers usually have CORS in place for security reasons.
If you really need the function you can simply make a nodejs server and proxy the request.
Or just move the logic to nodejs backend.
