### ISSUE TITLE
VTODO Support?

### ISSUE THREAD

**Issue by Estus-Dev** [natelindev/tsdav#192]
I'm looking to use this for tasks _(`VTODO` in the iCalendar standard)_ but the following exploratory code appears to only fetch `VEVENT`s.

```ts
    const calendars = await client.fetchCalendars();
    const tasks = await Promise.all(calendars.map(calendar => client.fetchCalendarObjects({ calendar })));
```

A quick search of the repo shows many hits for `VEVENT`, but only definitions for `VTODO`, which makes me think that `VTODO`s are not supported. Am I missing something?

If they're not currently supported, what is the path to supporting them? I've not dived too deep into the iCalendar or CalDAV standards myself, so any tips would be appreciated.

**Comment by natelindev** [comment]
by default `fetchCalendarObjects` will filter to only get `VEVENT`s
https://github.com/natelindev/tsdav/blob/a1e69654f628d9de4748f885d14e7ad6863d1978/src/calendar.ts#L240
you can write your own `comp-filter` to allow getting `VTODO` as well.
you can use https://tsdav.vercel.app/docs/helper to help write your own custom `comp-filter`.

**Comment by Estus-Dev** [comment]
Thanks, that's exactly what I needed!

For now I just took the linked filter, changed it to `VTODO`, and removed the time range. If I need something more sophisticated I'll update it later. 

```javascript
  // tsdav defaults to `VEVENT`s, we need `VTODO`s
  // See: https://github.com/natelindev/tsdav/blob/a1e69654f628d9de4748f885d14e7ad6863d1978/src/calendar.ts#L240-L269
  const filters = [
    {
      'comp-filter': {
        _attributes: { name: 'VCALENDAR' },
        'comp-filter': {
          _attributes: { name: 'VTODO' },
        },
      },
    },
  ];
```
