### ISSUE TITLE
Docs: How should we include Forward Email as a new provider)?

### ISSUE THREAD

**Issue by titanism** [natelindev/tsdav#199]
Hi there 👋 

We're the team behind @forwardemail which offers IMAP, POP3, SMTP, CalDAV and has [encrypted SQLite storage](https://forwardemail.net/en/blog/docs/best-quantum-safe-encrypted-email-service) using your in-memory password (only you have your password, we're 100% open-source and privacy-focused).

Your CalDAV (calendars) with us are stored in your own SQLite mailbox which is encrypted with your password (which only you have, and is only used/transferred in-memory while you're connected).

Here's the section of our FAQ which goes over CalDAV: <https://forwardemail.net/faq#do-you-support-calendars-caldav>

Curious if these are the only two places we'd need to submit a PR for inclusion, and if you had any thoughts on what verbiage we should add anywhere if any (besides obvious checkmarks and such in comparison matrix):

1) Cloud Providers page https://tsdav.vercel.app/docs/cloud%20providers

<img width="467" alt="Screen Shot 2024-07-18 at 5 04 04 AM" src="https://github.com/user-attachments/assets/dba50a0c-861d-4453-be8d-b2f5a8e342da">

2) Intro page https://tsdav.vercel.app/docs/intro

<img width="625" alt="Screen Shot 2024-07-18 at 5 05 51 AM" src="https://github.com/user-attachments/assets/1f8870f9-123d-49f1-bad3-e6ed99961d93">

---

We actually use `tsdav` for our tests!  Check it out <https://github.com/forwardemail/forwardemail.net/blob/a37eb9020d4647230aeaba9445348ff9387f71a5/test/caldav/index.js#L14C7-L14C12>

Also note that "google" and "apple" are not properly cased at <https://tsdav.vercel.app/docs/cloud%20providers>.

cc @natelindev

**Comment by natelindev** [comment]
thanks I'll take a look. 
I could include your service as one of the supported providers if it can work.

**Comment by natelindev** [comment]
can you provide me a test account or something, so that I can test it myself.

**Comment by natelindev** [comment]
@titanism my email is [linlilulll@gmail.com](mailto:linlilulll@gmail.com)

**Comment by natelindev** [comment]
fixed in v2.1.1
