### ISSUE TITLE
Support VTODO items

### ISSUE THREAD

**Issue by SamirSaidani** [natelindev/tsdav#20]
Just a feature request, it would be nice to be able to deal with tasks, and not only calendars. It means supporting VTODO entries.

**Comment by Kleisli** [comment]
VTODOs are basically also just CalendarObjects

**Comment by llldar** [comment]
Make sense, However, there are other more important bugs that need fixing. I'll take a look at this after other bugs are fixed.

**Comment by Kleisli** [comment]
@SamirSaidani You can fetch VTODO items by applying a filter

```
            await client.login();
            const calendars = await client.fetchCalendars();
            const calendarObjects = await client.fetchCalendarObjects({
                calendar: calendars[0],
                filters: [
                    {
                        type: 'comp-filter',
                        attributes: { name: 'VCALENDAR' },
                        children: [
                            {
                                type: 'comp-filter',
                                attributes: { name: 'VTODO' }
                            },
                        ],
                    },
                ]
            });
```

**Comment by natelindev** [comment]
Ability to specify custom prop and filter will be added in upcoming v1.2.0 release, you can specify whatever you want to fetch

**Comment by natelindev** [comment]
added in 2.0.0-rc.0

**Comment by Sewdohe** [comment]
> @SamirSaidani You can fetch VTODO items by applying a filter
> 
> ```
>             await client.login();
>             const calendars = await client.fetchCalendars();
>             const calendarObjects = await client.fetchCalendarObjects({
>                 calendar: calendars[0],
>                 filters: [
>                     {
>                         type: 'comp-filter',
>                         attributes: { name: 'VCALENDAR' },
>                         children: [
>                             {
>                                 type: 'comp-filter',
>                                 attributes: { name: 'VTODO' }
>                             },
>                         ],
>                     },
>                 ]
>             });
> ```

I came to the issues page of this hoping to find this EXACT snippet

**Comment by natelindev** [comment]
If you use v2.0 or later, You might want to convert the filters to new format using converter on tsdav website.
