### ISSUE TITLE
syncCalendars function problem

### ISSUE THREAD

**Issue by ErgoAvangenio** [natelindev/tsdav#208]
Hi, I found this library quite useful; however, I have a problem with the syncCalendar function. Apparently, the detailedResult variable is set to false instead of a boolean, causing an error when I try to set it to true. Any advice on how to resolve this in the meantime?
![Screenshot from 2024-08-20 07-20-42](https://github.com/user-attachments/assets/d96d157f-e245-4790-a69e-604f2a8006b8)
![Screenshot from 2024-08-20 07-21-15](https://github.com/user-attachments/assets/9c62bb2d-7615-4115-9f42-fe042e118f95)

**Comment by natelindev** [comment]
I will look into it in the future, meanwhile you can use type cast to work around this

**Comment by natelindev** [comment]
duplicate to #201
