### ISSUE TITLE
Calendar color property in fetchCalendars

### ISSUE THREAD

**Issue by nibdo** [natelindev/tsdav#60]
Hello, love tsdav, very easy to use.

I have just one question: would it be possible to add prop to get calendar color in fetchCalendars method?

Request payload would have this prop then:
<n0:calendar-color xmlns:n0="http://apple.com/ns/ical/"/>

Or maybe if not hard-coded to the method, it could be add via additional optional props, like you can customize other methods.

Thank you!

**Comment by natelindev** [comment]
Ability to specify custom prop will be added in upcoming v1.2.0 release.

**Comment by natelindev** [comment]
added in 2.0.0-rc.0
